# Generated by Django 5.1.5 on 2025-01-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruiker',
            name='rol',
            field=models.CharField(choices=[('eigenaar', 'Eigenaar'), ('instructeur', 'Instructeur'), ('klant', 'Klant')], default='klant', max_length=50),
        ),
    ]
