# Generated by Django 5.1.5 on 2025-01-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_gebruiker_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gebruiker',
            name='actief',
        ),
    ]
