# Generated by Django 5.1.5 on 2025-01-27 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_gebruiker_actief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lespakket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('omschrijving', models.TextField(blank=True, null=True)),
                ('aantal', models.PositiveIntegerField()),
                ('prijs', models.PositiveIntegerField()),
                ('soortles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gebruiker_Lespakket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lespakketten', to=settings.AUTH_USER_MODEL)),
                ('lespakket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gebruiker_lespakketten', to='user.lespakket')),
            ],
        ),
    ]
