# Generated by Django 5.1.5 on 2025-01-27 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_lespakket_gebruiker_lespakket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('kenteken', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Onderwerp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onderwerp', models.CharField(max_length=255)),
                ('omschrijving', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OphaalLocatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=7)),
                ('plaats', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Soort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Les',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lestijd', models.DateTimeField(blank=True, null=True)),
                ('doel', models.CharField(max_length=255)),
                ('geannuleerd', models.BooleanField()),
                ('reden_annuleren', models.TextField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les_auto', to='user.auto')),
                ('lespakket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessen', to='user.lespakket')),
                ('ophaal_locatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ophaal_locatie_les', to='user.ophaallocatie')),
            ],
        ),
        migrations.CreateModel(
            name='Les_Onderwerp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('les', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onderwerp', to='user.les')),
                ('onderwerp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les', to='user.onderwerp')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='soort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soort_auto', to='user.soort'),
        ),
        migrations.CreateModel(
            name='Ziekmelding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toelichting', models.TextField(blank=True, null=True)),
                ('van', models.DateTimeField(blank=True, null=True)),
                ('tot', models.DateTimeField(blank=True, null=True)),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziekmeldingen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
