# Generated by Django 5.1.5 on 2025-01-27 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_onderwerp_ophaallocatie_soort_les_les_onderwerp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruiker',
            name='gebruiker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessen', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
