# Generated by Django 5.1.5 on 2025-01-27 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_gebruiker_gebruiker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gebruiker',
            name='gebruiker',
        ),
        migrations.AddField(
            model_name='les',
            name='gebruiker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gebruiker_lessen', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
