# Generated by Django 5.1.5 on 2025-01-28 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_gebruiker_gebruiker_les_gebruiker'),
    ]

    operations = [
        migrations.AddField(
            model_name='soort',
            name='instructeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'instructeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soort_instructeur', to=settings.AUTH_USER_MODEL),
        ),
    ]
